asmond/asmond/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('login.urls')),
    path('framework/', include('framework.urls')),
    path('interface/', include('interface.urls')),
    path('login/', include('login.urls')),
    path('settings/', include('settings.urls')),
    path('admin/', admin.site.urls),
]

asmond/framework/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

asmond/interface/urls.py
from django.urls import path
from . import views

app_name = "interface"
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('homepage', views.homepage, name='homepage'),
    path('map', views.networkmap, name='networkmap'),
    path('devices', views.networkdevices, name='networkdevices'),
    path('problems', views.networkproblems, name='networkproblems'),
]

asmond/login/urls.py
from django.urls import path
from . import views

app_name = "login"
urlpatterns = [
    path('', views.login, name='login'),
]

asmond/settings/urls.py
from django.urls import path
from . import views

app_name = "settings"
urlpatterns = [
    path('', views.settings, name='settings'),
]

asmond/framework/models.py
from django.db import models

# Create your models here.

asmond/interface/models.py
from django.db import models

# Asmond Databases Listed Here


class NetworkDevices(models.Model):
    """
    Store journey time alert configuration
    """
    device_type = models.TextField(blank=True, verbose_name="Device Type", default=None, null=True)

    hostname = models.TextField(blank=True, default=None, verbose_name="Hostname")

    ip_address = models.TextField(blank=True, default=None, verbose_name="IP Address")

    mac_vendor = models.TextField(blank=True, default=None, verbose_name="MAC Vendor", null=True)

    device_level = models.IntegerField(default=1, verbose_name="Device Level")

    connects_to = models.TextField(blank=True, default=None, verbose_name="Connects To", null=True)


class NetworkOverview(models.Model):
    """
    Store number of certain devices
    """
    device_type = models.TextField(blank=True, verbose_name="Device Type", default=None, null=True)

    number_of_devices = models.IntegerField(default=1, verbose_name="Number Of Devices")


class NetworkProblems(models.Model):
    """
    Store problems found for each device
    """
    device = models.ForeignKey("interface.NetworkDevices", null=True, default=None, verbose_name="Devices", db_index=True, on_delete=models.CASCADE)

    device_problem = models.TextField(default=None, verbose_name="Device Problem")

    problem_severity = models.IntegerField(default=0, verbose_name="Problem Severity")


class NmapScan(models.Model):
    """
    Store journey time alert configuration
    """
    hostname = models.TextField(blank=True, default=None, verbose_name="Hostname")

    ip_address = models.TextField(blank=True, default=None, verbose_name="IP Address")

    port_number = models.IntegerField(default=0, null=True, verbose_name="Port Number")

    protocol_type = models.TextField(blank=True, default=None, verbose_name="Protocol Type (TCP/UDP)")

    device_state = models.TextField(blank=True, default=None, verbose_name="Device State")

    device_service = models.TextField(blank=True, default=None, verbose_name="Device Service")

    device_version = models.TextField(blank=True, default=None, verbose_name="Device Version")

asmond/login/models.py
from django.db import models

# Create your models here.

asmond/settings/models.py
from django.db import models

# Create your models here.

asmond/framework/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("Welcome to Framework.")

asmond/interface/views.py
import subprocess, os

from django.db.models.functions import Lower, Upper
from django.shortcuts import render
from .models import NetworkOverview, NetworkDevices, NetworkProblems, NmapScan
from .utils.usb_lookup import win_usb, linux_usb


def homepage(request):
    devices_overview = NetworkOverview.objects.all()
    devices_found = NetworkDevices.objects.all()
    device_problems = NetworkProblems.objects.all()

    device_problems = device_problems.order_by(Lower("problem_severity"))

    import socket
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("8.8.8.8", 80))
    ip_address = s.getsockname()[0]

    # If small USB is connected
    # Set small usb to True
    # Else set small usb to False

    if os.name == 'nt':
        print("OS: Windows")
        usb_sizes = win_usb()
    else:
        print("OS: Linux/Other")
        usb_sizes = linux_usb()

    small_usb = usb_sizes[0]
    midsize_usb = usb_sizes[1]
    large_usb = usb_sizes[2]
    enterprise_usb = usb_sizes[3]

    return render(request, "interface/homepage.html", {
        "devices_overview": devices_overview,
        "devices_found": devices_found,
        "device_problems": device_problems,
        "ip_address": ip_address,
        "small_usb": small_usb,
        "midsize_usb": midsize_usb,
        "large_usb": large_usb,
        "enterprise_usb": enterprise_usb
    })


def networkmap(request):
    devices_overview = NetworkOverview.objects.all()
    devices_found = NetworkDevices.objects.all()
    device_problems = NetworkProblems.objects.all()
    nmap_device = NmapScan.objects.all()

    import socket
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("8.8.8.8", 80))
    ip_address = s.getsockname()[0]

    return render(request, "interface/networkmap.html", {
        "devices_overview": devices_overview,
        "devices_found": devices_found,
        "device_problems": device_problems,
        "nmap_device": nmap_device,
        "ip_address": ip_address
    })


def networkdevices(request):
    devices_overview = NetworkOverview.objects.all()
    devices_found = NetworkDevices.objects.all()
    device_problems = NetworkProblems.objects.all()
    nmap_device = NmapScan.objects.all()

    return render(request, "interface/networkdevices.html", {
        "devices_overview": devices_overview,
        "devices_found": devices_found,
        "device_problems": device_problems,
        "nmap_device": nmap_device
    })


def networkproblems(request):
    devices_overview = NetworkOverview.objects.all()
    devices_found = NetworkDevices.objects.all()
    device_problems = NetworkProblems.objects.all()

    device_problems = device_problems.order_by(Lower("problem_severity"))

    #subprocess.call(['./problems.sh'])

    return render(request, "interface/networkproblems.html", {
        "devices_overview": devices_overview,
        "devices_found": devices_found,
        "device_problems": device_problems
    })

asmond/login/views.py
from django.shortcuts import render


def login(request):
    return render(request, "login/login.html")

asmond/settings/views.py
from django.shortcuts import render


def settings(request):
    return render(request, "settings/settings.html")

asmond/framework/templates/framework/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'framework/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'framework/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'framework/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'framework/css/jquery.datetimepicker.css' %}">

    <link rel="icon" type="image/png" href="{% static 'framework/img/favicon/asmond-favicon.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'framework/img/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'framework/img/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'framework/img/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'framework/img/favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'framework/img/favicon/safari-pinned-tab.svg' color='#5bbad5' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <script src="{% static 'framework/js/jquery-3.1.0.min.js' %}"></script>
    <script src="{% static 'framework/js/jquery.datetimepicker.js' %}"></script>
    <script src="{% static 'framework/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'framework/js/bootbox.min.js' %}"></script>
    <script src="{% static 'framework/js/csrf.js' %}"></script>

    {% block head %}
    {% endblock %}

    <title>{% block title %}{% endblock %} - Asmond Demo</title>
</head>
<body>
<nav class="navbar navbar-inverse" style="background-color: #2f2f2f;">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header" style="padding-left:15px; padding-right:2%;">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url 'interface:homepage' %}">
                <img src="{% static 'framework/img/asmond-web-logo-inverted-v4.png'%}" style="padding-top:3px;">
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="{% block networkmap-active %}{% endblock %}"><a href="{% url 'interface:networkmap' %}">Map</a></li>
            </ul>

            <ul class="nav navbar-nav">
                <li class="{% block networkdevices-active %}{% endblock %}"><a href="{% url 'interface:networkdevices' %}">Devices</a></li>
            </ul>

            <ul class="nav navbar-nav">
                <li class="{% block networkproblems-active %}{% endblock %}"><a href="{% url 'interface:networkproblems' %}">Problems</a></li>
            </ul>

            <ul class="nav navbar-nav visible-xs hidden-sm">
                <li class="{% block login-active %}{% endblock %}"><a href="{% url 'login:login' %}">Logout</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right hidden-xs visible-sm visible-md visible-lg">
                <li class="{% block logout %}{% endblock %}">
                    <a href="{% url 'login:login' %}">
                        <img src="{% static 'framework/img/logout.png'%}" onmouseover="this.src='{% static 'framework/img/logout2.png'%}';"
                             onmouseout="this.src='{% static 'framework/img/logout.png'%}';" style=" margin-top:-25px; width:40px; height:40px; margin-bottom:-20px;">
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="{% block settings-active %}{% endblock %}"><a href="{% url 'settings:settings' %}">Settings</a></li>
            </ul>


        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="container">
    {% block page-content %}
    {% endblock %}
</div>
</body>
</html>

asmond/framework/templates/framework/login-base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{% static 'framework/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'framework/css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'framework/css/base.css' %}">
        <link rel="stylesheet" href="{% static 'framework/css/jquery.datetimepicker.css' %}">

        <script src="{% static 'framework/js/jquery-3.1.0.min.js' %}"></script>
        <script src="{% static 'framework/js/jquery.datetimepicker.js' %}"></script>
        <script src="{% static 'framework/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'framework/js/bootbox.min.js' %}"></script>
        <script src="{% static 'framework/js/csrf.js' %}"></script>

        {% block head %}
        {% endblock %}

        <title>{% block title %}{% endblock %} - Network Defender</title>
    </head>

    <body>
        <nav class="navbar navbar-inverse" style="background-color: #2f2f2f;">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header" style="float:none;">
                    <div style="text-align:center;">
                        <img src="{% static 'framework/img/asmond-web-logo-inverted-v3.png'%}">
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </nav>
        <div class="container">
            {% block page-content %}
            {% endblock %}
        </div>
    </body>
</html>

asmond/interface/templates/interface/asmond-base.html
{% extends 'framework/base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'interface/css/asmond.css' %}">
{% endblock %}

{% block interface-active %}active{% endblock %}

{% block page-content %}
    {% block interface-content %}
    {% endblock %}
{% endblock %}

asmond/interface/templates/interface/homepage.html
{% extends 'interface/asmond-base.html' %}
{% load static %}
{% load humanize %}

{% block head %}
{{ block.super }}

{% endblock %}

{% block title %}Homepage{% endblock %}

{% block homepage-active %}active{% endblock %}

{% block interface-content %}

<link rel="stylesheet" href="{% static 'interface/css/homepage.css' %}">
<link rel="stylesheet" href="{% static 'interface/css/jQuery-plugin-progressbar.css' %}">
<script src="{% static 'interface/js/smartresize.js' %}"></script>
<script src="{% static 'interface/js/jQuery-plugin-progressbar.js' %}"></script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
  google.charts.load('current', {'packages':['corechart']});
  google.charts.setOnLoadCallback(drawChart);

  function drawChart() {

    var data = google.visualization.arrayToDataTable([
      ['Problem', 'Amount'],
      ['General Spam',      12],
      ['Phishing',          10],
      ['Pharming',          5],
      ['Ads',               5],
      ['Spoofed Emails',    2],
      ['Explicit Spam',     2]
    ]);

    var options = {
      width: '100%',
      height: '100%',
      pieSliceText: 'value',
      legend: {
        position: 'right',
        maxLines: '5',
        alignment: 'right'
      },
      chartArea: { width: "100%", height: "70%" }
    };

    var chart = new google.visualization.PieChart(document.getElementById('piechart'));

    chart.draw(data, options);

    $(window).smartresize(function () {
        chart.draw(data, options);
    });
  }
</script>


<div>
    <!-- IP Address -->
    <div class="panel panel-default visible-xs" style="height:100%; margin-top:10px; text-align:center;">
        <div class="panel-body" style="height:100%;">
            <label>Web Interface: {{ ip_address }}:8000</label>
        </div>
    </div>

    <!-- Homepage Test -->
    <div style="width:100%;">
        <!-- Top 2 Panels -->
        <div>
            <!-- Top Left Panel -->
            <div class="left-panel">
                {% if small_usb == True %}
                <div class="panel panel-success" style="height:100%; margin-top:10px;">
                    <div class="panel-heading" style="text-align:center;">
                        <label>Small Business Module</label>
                    </div>
                    <div class="panel-body">
                        <label>Firewall:</label> Running<br>
                        <label>Status:</label> OK
                    </div>
                </div>
                {% else %}
                <div class="panel panel-danger" style="height:100%; margin-top:10px;">
                    <div class="panel-heading" style="text-align:center;">
                        <label>Small Business Module</label>
                    </div>
                    <div class="panel-body" style="text-align:center; padding-top:25px;">
                        <label>Module Offline</label>
                    </div>
                </div>
                {% endif %}
            </div>
            <!-- Top Right Panel -->
            <div class="right-panel">
                {% if midsize_usb == True %}
                <div class="panel panel-danger" style="height:100%; margin-top:10px;">
                    <div class="panel-heading" style="text-align:center;">
                        <label>Midsize Business Module</label>
                    </div>
                    <div class="panel-body">
                        <label>Anti-Spam:</label> Running<br>
                        <label>Status:</label> Problems Found!
                    </div>
                </div>
                {% else %}
                <div class="panel panel-warning" style="height:100%; margin-top:10px;">
                    <div class="panel-heading" style="text-align:center;">
                        <label>Midsize Business Module</label>
                    </div>
                    <div class="panel-body" style="text-align:center; padding-top:25px;">
                        <label>Module Offline</label>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>


        <!-- Middle 2 Panels -->
        <div>
           <!-- Middle Left Panel -->
            <div class="left-panel">
                {% if large_usb == True %}
                <div class="panel panel-success" style="height:100%; margin-top:10px;">
                    <div class="panel-heading" style="text-align:center;">
                        <label>Large Business Module</label>
                    </div>
                    <div class="panel-body">
                        <label>Deep Packet Inspection:</label> Running<br>
                        <label>Status:</label> OK
                    </div>
                </div>
                {% else %}
                <div class="panel panel-warning" style="height:100%; margin-top:10px;">
                    <div class="panel-heading" style="text-align:center;">
                        <label>Large Business Module</label>
                    </div>
                    <div class="panel-body" style="text-align:center; padding-top:25px;">
                        <label>Module Offline</label>
                    </div>
                </div>
                {% endif %}
            </div>
            <!-- Middle Right Panel -->
            <div class="right-panel">
                {% if enterprise_usb == True %}
                <div class="panel panel-success" style="height:100%; margin-top:10px;">
                    <div class="panel-heading" style="text-align:center;">
                        <label>Enterprise Module</label>
                    </div>
                    <div class="panel-body">
                        <label>Honeypot:</label> Running<br>
                        <label>Status:</label> OK
                    </div>
                </div>
                {% else %}
                <div class="panel panel-warning" style="height:100%; margin-top:10px;">
                    <div class="panel-heading" style="text-align:center;">
                        <label>Enterprise Business Module</label>
                    </div>
                    <div class="panel-body" style="text-align:center; padding-top:25px;">
                        <label>Module Offline</label>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>

        <!-- Bottom 2 Panels -->
        <div>
            <!-- Bottom Left Panel -->
            {% if small_usb == True %}
            <div class="left-panel" style="height:300px;">
                <div class="panel panel-default" style="height:100%; margin-top:10px;">
                    <div class="panel-heading" style="text-align:center;">
                        <label>Security Score</label>
                    </div>
                    <div class="panel-body">

                        <!-- Security Score 2 -->
                        <div style="width:100%;">
                            <div style="display: table; margin: 0 auto;">
                                {% if midsize_usb == True %}
                                <div class="progress-bar position" data-percent="80" data-duration="2000"></div>
                                {% else %}
                                <div class="progress-bar position" data-percent="100" data-duration="2000"></div>
                                {% endif %}
                                <script>
                                    $(".progress-bar").loading();
                                </script>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% else %}
            <div class="bottom-panel">
                <div class="panel panel-danger" style="height:100%; margin-top:10px;">
                    <div class="panel-heading" style="text-align:center;">
                        <label>Security Score & Network Problems</label>
                    </div>
                    <div class="panel-body" style="text-align:center; padding-top:25px; height:100px;">
                        <label>Error:</label> Small business module is not online!<br>
                        Please connect small business module and try again...
                    </div>
                </div>
            </div>
            {% endif %}


            <!-- Bottom Right Panel -->
            {% if midsize_usb == True %}
            <div class="right-panel" style="height:300px;">
                <div class="panel panel-default" style="height:100%; margin-top:10px;">
                    <div class="panel-heading" style="text-align:center;">
                        <label>Network Problems</label>
                    </div>
                    <div class="panel-body">
                        <div>
                            <!-- Problems Graph -->
                            <div id="piechart" style="height:100%; width: 100%;"></div>
                        </div>
                    </div>
                </div>
            </div>
            {% elif small_usb == True %}
            <div class="right-panel" style="height:300px;">
                <div class="panel panel-success" style="height:100%; margin-top:10px;">
                    <div class="panel-heading" style="text-align:center;">
                        <label>Network Problems</label>
                    </div>
                    <div class="panel-body" style="text-align:center; padding-top:110px;">
                        <label>No Problems Found!</label>
                    </div>
                </div>
            </div>
            {% else %}
            <div>
                <!-- Nothing -->
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

asmond/interface/templates/interface/networkdevices.html
{% extends 'interface/asmond-base.html' %}
{% load static %}
{% load humanize %}

{% block head %}
{{ block.super }}

{% endblock %}

{% block title %}Network Devices{% endblock %}

{% block networkdevices-active %}active{% endblock %}

{% block interface-content %}
    <div class="col-md-8 col-md-offset-2 col-sm-12 col-xs-12">
    {% if devices_found != None %}
    {% for device in devices_found %}
        <div class="panel panel-default" style="height:100%; margin-top:10px;">
            <div class="panel-heading">
                <label>{{ device.device_type }} Device Name:</label> "{{ device.hostname }}"
            </div>
            <div class="panel-body">
                <label>IP Address:</label> {{ device.ip_address }}
                <br>
                <label>MAC Vendor:</label> {{ device.mac_vendor }}
            </div>
        </div>
    {% endfor %}
    {% else %}
        <br>
        <div style="text-align: center;">
            <label>No Device Data Found</label>
        </div>
    {% endif %}
    </div>
    <div>
        {% for mapped in nmap_device %}
        TEMP DIV: {{ mapped.hostname }}
        {% endfor %}
    </div>
{% endblock %}

asmond/interface/templates/interface/networkmap.html
{% extends 'interface/asmond-base.html' %}
{% load static %}
{% load humanize %}

{% block head %}
{{ block.super }}

{% endblock %}

{% block title %}Asmond Dashboard{% endblock %}

{% block networkmap-active %}active{% endblock %}

{% block interface-content %}

<div>
    <div class="panel panel-default visible-xs" style="height:100%; margin-top:10px; text-align:center;">
        <div class="panel-body">
            <label>Web Interface: {{ ip_address }}:8000</label>
        </div>
    </div>

    <!-- No Device Levels Found -->
    {% if devices_found != None %}
        {% for device in devices_found %}
            {% if device.device_level == 1 %}
            {% elif device.device_level == 2 %}
            {% elif device.device_level == 3 %}
            {% else %}
                <div class="panel panel-default" style="height:100%; margin-top:10px; text-align:center;">
                    <div class="panel-body">
                        <label>No Devices Levels Found</label>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}


    <!-- Level 1 - Router Tier -->
    <div>
        <div class="panel panel-primary" style="height:100%; margin-top:10px; margin-bottom:0px;">
            <div class="panel-heading" style="text-align:center;">
                <label>Level 1 Device</label>
            </div>
        </div>
        <div class="panel panel-default" style="height:100%;">
            {% if devices_found != None %}
                {% for device in devices_found %}
                    {% if device.device_level == 1 %}
                        <div class="panel-heading">
                            <label>{{ device.device_type }} Name:</label> "{{ device.hostname }}"
                        </div>
                        <div class="panel-body">
                            <label>IP Address:</label> {{ device.ip_address }}
                            <br>
                            <label>MAC Vendor:</label> {{ device.mac_vendor }}
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </div>

    <!-- Level 2 - Devices Connected To Router -->
    <div>
        <div class="panel panel-primary" style="height:100%; margin-top:10px; margin-bottom:0px;">
            <div class="panel-heading panel-primary" style="text-align:center;">
                <label>Level 2 Devices</label>
            </div>
        </div>
        <div class="panel panel-default" style="height:100%;">
            {% if devices_found != None %}
                {% for device in devices_found %}
                    {% if device.device_level == 2 %}
                        <div class="panel-heading">
                            <label>{{ device.device_type }} Name:</label> "{{ device.hostname }}"
                        </div>
                        <div class="panel-body">
                            <label>IP Address:</label> {{ device.ip_address }}
                            <br>
                            <label>MAC Vendor:</label> {{ device.mac_vendor }}
                            <br>
                            <label>Connects To:</label> "{{ device.connects_to }}"
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </div>

    <!-- Level 3 - Devices Connected To Devices -->
    <div>
        <div class="panel panel-primary" style="height:100%; margin-top:10px; margin-bottom:0px;">
            <div class="panel-heading panel-primary" style="text-align:center;">
                <label>Level 3 Devices</label>
            </div>
        </div>
        <div class="panel panel-default" style="height:100%;">
            {% if devices_found != None %}
                {% for device in devices_found %}
                    {% if device.device_level == 3 %}
                        <div class="panel-heading">
                            <label>{{ device.device_type }} Name:</label> "{{ device.hostname }}"
                        </div>
                        <div class="panel-body">
                            <label>IP Address:</label> {{ device.ip_address }}
                            <br>
                            <label>MAC Vendor:</label> {{ device.mac_vendor }}
                            <br>
                            <label>Connects To:</label> "{{ device.connects_to }}"
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

asmond/login/templates/login/login-base.html
{% extends 'framework/login-base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'login/css/login.css' %}">
{% endblock %}

{% block page-content %}
    {% block login-content %}
    {% endblock %}
{% endblock %}

asmond/login/templates/login/login.html
{% extends 'login/login-base.html' %}
{% load static %}
{% load humanize %}

{% block head %}
{{ block.super }}

{% endblock %}

{% block title %}Login{% endblock %}

{% block login-content %}
    <div class="col-md-8 col-md-offset-2 col-sm-12 col-xs-12">
    <div class="container-fluid" style="background:#e6e6e6">
            <br>
            <p class="text-center"><b>Login</b></p>

            <div class="form-group {% if form.errors.email %}has-error{% endif %}">
                <label class="control-label" for="email">Administrator Username</label>
                <div class="controls">
                    <input class="form-control" type="text" id="email" name="email"
                           placeholder=". . ." required autofocus>

                    {% if form.errors.email %}
                        <span class="help-block" >{{ form.errors.email.0 }}</span>
                    {% endif %}
                </div>
            </div>

            <div class="form-group {% if form.errors.password %}has-error{% endif %}">
                <label class="control-label" for="password">Administrator Password</label>
                <div class="controls">
                    <input class="form-control" type="password" value="{{ form.data.password }}" id="password"
                           name="password" placeholder=". . ." required>

                    {% if form.errors.password %}
                        <span class="help-block" >{{ form.errors.password.0 }}</span>
                    {% endif %}
                </div>
            </div>

            <div class="text-center">
                <a href="{% url 'interface:homepage' %}">
                    <button type="submit" class="btn-space btn btn-primary btn-sm">Login</button>
                </a>
            </div>
            <br>
        </div>
    </div>
{% endblock %}